Cuquantum backend (#84)
* Add Docker of cuStatevector version (WIP)

* Small fixes

* update Dockerfile

* Now use qsim as the backend. Looks like cuquantum is too primitive at the moment
and cannot install outside of conda.

* WIP: cannot install cuQuantum at the moment

* .

* a small fix and now cuquantum builds.

* Cleanups.

* qsim_nvidia -> cirq

* fix cuQuantum download url

* add pycall for gem

* move

* .

* avoid the following error:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

* test circuit

* .

* Update qni-cirqbridge.

* qsim GPU support requires to build from the source

* Updated cirqbridge. qsimcirq now runs on the GPU.

* Remove empty circuits.

* .

* .

* rename to cirq to cirq_backend

* Solve conflicts when merging from upstream

* Solve conflicts when merging from upstream

* back to my backend.

* .

* backout to my cirqbridge.

* .

* Impliment |0>, |1> initializations and H gate.

Co-authored-by: Yasuhito Takamiya <yasuhito@hey.com>